### ISSUE TITLE
Issue with ThreeTen bp lib dependency

### ISSUE THREAD

**Issue by st-wong** [proximax-storage/java-chain-xipfs-sdk#34]
When projects utilize the SDK, it seems to require the dependency from [ThreeTen](https://github.com/ThreeTen/threetenbp) for it to work.
Error received during compilation:
```java
Caused by: java.lang.ClassNotFoundException: org.threeten.bp.temporal.TemporalUnit
```

**Comment by tonowie** [comment]
can you please paste full stack trace?

**Comment by tonowie** [comment]
not needed after all I was able to find where the backport is used. This is actually issue with the chain SDK. Raised issue for that (referenced above) and once fix is made I will make sure updated dependency is used by xipfs

**Comment by tonowie** [comment]
vixed in https://github.com/proximax-storage/java-chain-xipfs-sdk/releases/tag/0.6.1
